### ISSUE TITLE
Remove edit this page on google search 

### ISSUE THREAD

**Issue by lyubar** [GoInterject/GoInterject.github.io#18]
File: [schemas/search.md](https://docs.gointerject.com/schemas/search.html)

![image](https://user-images.githubusercontent.com/1638992/51193144-02f42e80-189d-11e9-964f-057aee33c2d3.png)

**Comment by derekolson09** [comment]
Will work this out, my priority has shifted off the website development at the moment, but will return.

**Comment by derekolson09** [comment]
Resolved for patch 2
