### ISSUE TITLE
when a page doesn't exists we should create an issue instead of going to 404

### ISSUE THREAD

**Issue by lyubar** [GoInterject/GoInterject.github.io#19]
![image](https://user-images.githubusercontent.com/1638992/51193255-48186080-189d-11e9-8153-06959730c1aa.png)

This is what the docker site does

![image](https://user-images.githubusercontent.com/1638992/51193323-74cc7800-189d-11e9-8654-37a614ae8a73.png)

**Comment by derekolson09** [comment]
I have to alter the way the 404 page is being rendered, that will take some time. I will work on this once my priorities shift back to website development.
