### ISSUE TITLE
Document how to remove a database from initial import

### ISSUE THREAD

**Issue by lyubar** [GoInterject/GoInterject.github.io#30]
File: [bApps/bFinancials/InitialDataLoad.md](https://docs.gointerject.com/bApps/bFinancials/InitialDataLoad.html)

Between 1a and 1b we need to insert the following:
-------------------------------------------------------------------------------------

sub-step How to limit import to specific databases

Interject will import all Epicor database that are connected to the Master Epicor database. To see all the databases that interject will import run the following select. 

`
SELECT * FROM [ImportERP].[SourceDatabaseList]
`

To prevent a database from being imported marked that database as inactive. Below is a script to make this change. 

```
UPDATE [ImportERP].[SourceDatabaseList]
SET [Inactive] = 1 
WHERE [DatabaseName] = '[DeactivateDatabase2]'
```

If a database is made inactive after the initial load, data that was import to that time will still be in interject and can be used to report from. However new data will stop flowing into interject.

**Comment by bille-interject** [comment]
Issue addressed in docs site.
