### ISSUE TITLE
Add another parameter to 1c execution script

### ISSUE THREAD

**Issue by lyubar** [GoInterject/GoInterject.github.io#31]
File: [bApps/bFinancials/InitialDataLoad.md](https://docs.gointerject.com/bApps/bFinancials/InitialDataLoad.html)

Add another parameter to 1c execution script as shown below

--Specify historical periods in which to seed Interject Data Store
EXEC [Custom].[ERP_InstallScript3_ReportingImport]
    @ReportingImport_YearBegin     = 'INSERT>YYYY'
   ,@ReportingImport_YearEnd        = 'INSERT>YYYY'
   ,@ImportBudget                           = 'Yes'

**Comment by bille-interject** [comment]
Param added 4/29/2019
