### ISSUE TITLE
Add new deploy version 1.0.9

### ISSUE THREAD

**Issue by lyubar** [GoInterject/GoInterject.github.io#32]
File: [bApps/bFinancials/Technical-Install.md](https://docs.gointerject.com/bApps/bFinancials/Technical-Install.html)

Below is a link to the latest script 1.0.9 please add it to the documentation site
https://drive.google.com/file/d/1u-rx7IDaE3fO4DwdwDQUmOcR_kjKpM8T/view?usp=sharing

**Comment by bille-interject** [comment]
Script version and script link updated 4/29/2019
