### ISSUE TITLE
Add new deploy version 1.0.5

### ISSUE THREAD

**Issue by lyubar** [GoInterject/GoInterject.github.io#33]
File: [bApps/bFinancials/Technical-Install.md](https://docs.gointerject.com/bApps/bFinancials/Technical-Install.html)

Below is a link to the latest script 1.0.9 please add it to the documentation site for FRx_Transfer

https://drive.google.com/file/d/16Hzm3DT5Pzm5zDexsSF3Kf3Fl81sM9NE/view?usp=sharing

**Comment by bille-interject** [comment]
Script version updated and link added 4/29/2019
