### ISSUE TITLE
add comma

### ISSUE THREAD

**Issue by lyubar** [GoInterject/GoInterject.github.io#34]
File: [bApps/bFinancials/Technical-Install.md](https://docs.gointerject.com/bApps/bFinancials/Technical-Install.html)

now 
EXEC [Custom].[Interject_SetupScript1_Security]
	@MasterEpicorDatabase = 'samplemasterdb'
	@CertificatePassword =  'myPassword1234'

need to add a comma before CertificatePassword 
EXEC [Custom].[Interject_SetupScript1_Security]
	@MasterEpicorDatabase = 'samplemasterdb'
	,@CertificatePassword =  'myPassword1234'

**Comment by bille-interject** [comment]
Fixed! 5/2/19
