### ISSUE TITLE
Update script names and order

### ISSUE THREAD

**Issue by lyubar** [GoInterject/GoInterject.github.io#35]
File: [bApps/bFinancials/InitialDataLoad.md](https://docs.gointerject.com/bApps/bFinancials/InitialDataLoad.html)

here is the new order and names of the scripts
	
	EXEC [Custom].[ERP_InstallScript1_DatabaseConfig]
		 @MasterEpicorDatabase		= '[DemoControl]'
		,@DefaultDatabaseNameSource = '[DemoDist]'

	EXEC [Custom].[ERP_InstallScript2_EpicorImport]
	
	EXEC [Custom].[ERP_InstallScript3_GroupingImport]

	EXEC [Custom].[ERP_InstallScript4_ReportingImport]
		 @ReportingImport_YearBegin	= '2000'
		,@ReportingImport_YearEnd	= '2016'
		,@ImportBudget				= 'Yes'

	EXEC [Custom].[ERP_InstallScript5_SetupJobs]
*/

**Comment by bille-interject** [comment]
Done 4/2/19.
@lyubar double check the documentation page, please. I was having some copy paste issues with VS code. Thanks.
