### ISSUE TITLE
Remove Use [Interject_Reporting] from Initial.Interject_Reporting.sql 

### ISSUE THREAD

**Issue by ArnieCilliers** [GoInterject/GoInterject.github.io#39]
File: [bApps/bFinancials/Technical-Install.md](https://docs.gointerject.com/bApps/bFinancials/Technical-Install.html)

The database name is not always going to be [Interject_Reporting] and it is not clear that the DBA might need to change this statement in the provided SQL Script.

**Comment by bille-interject** [comment]
Thank you. I'll check on this issue and get the docs updated.
-B.E.

**Comment by bille-interject** [comment]
This issue has been resolved.
