### ISSUE TITLE
update 'Updating Interject' page

### ISSUE THREAD

**Issue by adamrgointerject** [GoInterject/GoInterject.github.io#40]
We only have pages for '[Installing Interject](https://docs.gointerject.com/wAbout/SingleUser.html)' and '[Uninstalling Interject](https://docs.gointerject.com/wAbout/Uninstalling.html)' 

As of v2.3.18.0 there is a new way to update Interject. We need to document the current process. 
_Note: We may need a section about having to uninstall Interject completely if user has version <= 2.3.0.15._

**Current Process of Updating Interject**
_This version of updating Interject is available starting in v2.3.18.0_

1. In the Interject ribbon click the 'Check For Updates' button
2. The window that opens will show if a new version is available. If a version is available then click 'Get Update' and the Addin Manager will open to complete the check for updates process
![image](https://user-images.githubusercontent.com/39102276/58354851-74358680-7e27-11e9-92e7-826fa1b1583b.png)
4. In Addin Manager, click 'Update' and the new version will start downloading.
5. After the download is complete, if Excel is still running then Addin Manager will wait for you to close Excel before launching the installer. You can force close Excel if you don't need to save any of your work.
6. The installer will launch after Excel is closed and then you continue with the installation wizard to complete installing the newest version of interject

**Comment by adamrgointerject** [comment]
@derekolson09 this page, https://docs.gointerject.com/wAbout/Updating-INTERJECT.html, needs to be updated with the new check for updates process (outlined above)

**Comment by derekolson09** [comment]
@adamrgointerject I agree. I will have the students look at doing this as their first project for rehauling a current documentation page.

**Comment by derekolson09** [comment]
completed in patch-3.3
